### ISSUE TITLE
Hyper-parameters for training

### ISSUE THREAD

**Issue by YehLi** [AAboys/MobileFormer#1]
Thanks for your great job. Do you plan to release the training code?

**Comment by AAboys** [comment]
The training command is added. Default train.py in timm is used.

**Comment by YehLi** [comment]
Thanks for your reply, do you use the same mixup, aa, reprob for other Mobile-Former models?

**Comment by AAboys** [comment]
it may change for smaller models, which model do you looking for?

**Comment by wangwuwei** [comment]
> it may change for smaller models, which model do you looking for?

could you please provide the training commands of other models such as 96m?

**Comment by AAboys** [comment]
training setup for 96m is added.
